name: check-milestone-label

permissions: {}

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - labeled
      - unlabeled
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_labels:
    name: Check milestone label for pull request
    runs-on:
      group: kyverno-default
    if: ${{ github.actor != 'dependabot[bot]' }}  # dependabot prs do not have to be in milestone
    steps:
      - name: require milestone label for pull request
        uses: docker://agilepathway/pull-request-label-checker:v1.6.0@sha256:b2989dae0ef86aaa09bae3e4237a87d3367e2830ea2e313d0b798a38e4446db1
        with:
          prefix_mode: true
          one_of: "milestone"
          repo_token: ${{ secrets.GITHUB_TOKEN }}